{
  "headers": {
    "content-type": "application/json; charset=utf-8",
    "date": "Fri, 18 Dec 2020 17:48:51 GMT",
    "etag": "W/\"71-p7K+rouVe6oWHpznv2l8HNaFEDM\"",
    "expires": "-1",
    "pragma": "no-cache",
    "server": "nginx",
    "set-cookie": "_csrf=J8uCc9qu9l-DcZrEcYNPR4E_; Path=/; HttpOnly; Secure",
    "set-cookie": "XSRF-TOKEN=U36h0Dk3-yLNkjRQOuBdWUnJWV7zhUIh_duk; Path=/; Secure",
    "set-cookie": "_csrf=Vqx7veCOWLAeSf_q_VPI7hgI; Path=/; HttpOnly; Secure",
    "set-cookie": "mulesoft.sess=eyJpZCI6ImVQRzJSZ3JaTm5sMnpJaklrck1uQlE3aXZ2TEgyQjhrIiwicGFzc3BvcnQiOnsidXNlciI6eyJ1c2VyX2lkIjoiZWQwY2VlNjktYmI5YS00MmExLWIwZjEtYTBiOWQyOWJjNGNiIn19fQ==; path=/; secure; httponly",
    "set-cookie": "mulesoft.sess.sig=PnCSsfiVz1rMCww4RUxqFLrQKA8; path=/; secure; httponly",
    "strict-transport-security": "max-age=31536000; includeSubDomains",
    "vary": "X-HTTP-Method-Override, Accept-Encoding",
    "x-anypnt-trx-id": "fd41aab52880a302",
    "x-content-type-options": "nosniff",
    "x-dns-prefetch-control": "off",
    "x-download-options": "noopen",
    "x-frame-options": "SAMEORIGIN",
    "x-frame-options": "SAMEORIGIN",
    "x-ratelimit-limit": "500",
    "x-ratelimit-remaining": "499",
    "x-ratelimit-reset": "1608313740",
    "x-request-id": "fd41aab52880a302",
    "x-xss-protection": "1; mode=block",
    "content-length": "113",
    "connection": "keep-alive"
  },
  "reasonPhrase": "OK",
  "statusCode": 200
}